#include <iostream>
using namespace std;
int main() {
float numeros;
//Mostrar en pantalla
cout<<"Ingrese el numero"<<endl;
cin>>numeros;
if(numeros==0)cout<< numeros<<" = cero"<<endl;
if (numeros==1)cout<< numeros<<" = uno"<<endl;
if (numeros==2)cout<< numeros<<" = dos"<<endl;
if(numeros==3)cout<< numeros<<" = tres"<<endl;
if(numeros==4)cout<< numeros<<" = cuatro"<<endl;
if(numeros==5)cout<< numeros<<" = cinco"<<endl;
if(numeros==6)cout<< numeros<<" = seis"<<endl;
if(numeros==7)cout<< numeros<<" = siete"<<endl;
if(numeros==8)cout<< numeros<<" = ocho"<<endl;
if(numeros==9)cout<< numeros<<" = nueve"<<endl;
if(numeros==10)cout<< numeros<<" = diez"<<endl;
if(numeros==11)cout<< numeros<<" = once"<<endl;
if(numeros==12)cout<< numeros<<" = doce"<<endl;
if(numeros==13)cout<< numeros<<" = trece"<<endl;
if(numeros==14)cout<< numeros<<" = catorce"<<endl;
if(numeros==15)cout<< numeros<<" = quice"<<endl;
if(numeros==16)cout<< numeros<<" = dieciseis"<<endl;
if(numeros==17)cout<< numeros<<" = diecisiete"<<endl;
if(numeros==18)cout<< numeros<<" = dieciocho"<<endl;
if(numeros==19)cout<< numeros<<" = diecinueve"<<endl;
if(numeros==20)cout<< numeros<<" = veinte"<<endl;
if(numeros==21)cout<< numeros<<" = veintiuno"<<endl;
if(numeros==22)cout<< numeros<<" = veintidos"<<endl;
if(numeros==23)cout<< numeros<<" = veintitres"<<endl;
if(numeros==24)cout<< numeros<<" = veinticuatro"<<endl;
if(numeros==25)cout<< numeros<<" = veinticinco"<<endl;
if(numeros==26)cout<< numeros<<" = veintiseis"<<endl;
if(numeros==27)cout<< numeros<<" = veintisiete"<<endl;
if(numeros==28)cout<< numeros<<" = veintiocho"<<endl;
if(numeros==29)cout<< numeros<<" = veintinueve"<<endl;
if(numeros==30)cout<< numeros<<" = treinta"<<endl;
if(numeros==31)cout<< numeros<<" = treinta y uno"<<endl;
if(numeros==32)cout<< numeros<<" = treinta y dos"<<endl;
if(numeros==33)cout<< numeros<<" =treinta y tres"<<endl;
if(numeros==34)cout<< numeros<<" = treinta y cuatro"<<endl;
if(numeros==35)cout<< numeros<<" =treinta y cinco"<<endl;
if(numeros==36)cout<< numeros<<" =treinta y seis"<<endl;
if(numeros==37)cout<< numeros<<" = treinta y siete"<<endl;
if(numeros==38)cout<< numeros<<" = treinta y ocho"<<endl;
if(numeros==39)cout<< numeros<<" = treinta y nueve"<<endl;
if(numeros==40)cout<< numeros<<" = cuarenta"<<endl;
if (numeros==41)cout<< numeros<<" = cuarenta y uno"<<endl;
if (numeros==42)cout<< numeros<<" = cuarenta y dos"<<endl;
if(numeros==43)cout<< numeros<<" = cuarenta y tres"<<endl;
if(numeros==44)cout<< numeros<<" = cuarenta y cuatro"<<endl;
if(numeros==45)cout<< numeros<<" = cuarenta y cinco"<<endl;
if(numeros==46)cout<< numeros<<" = cuarenta y seis"<<endl;
if(numeros==47)cout<< numeros<<" = cuarenta y siete"<<endl;
if(numeros==48)cout<< numeros<<" = cuarenta y ocho"<<endl;
if(numeros==49)cout<< numeros<<" = cuarenta y nueve"<<endl;
if(numeros==50)cout<< numeros<<" = cincuenta"<<endl;
if(numeros==51)cout<< numeros<<" = cincuenta y uno"<<endl;
if(numeros==52)cout<< numeros<<" = cincuenta y dos"<<endl;
if(numeros==53)cout<< numeros<<" = cincuenta  y tres"<<endl;
if(numeros==54)cout<< numeros<<" = cincuenta y  cuatro"<<endl;
if(numeros==55)cout<< numeros<<" =cincuenta y cinco"<<endl;
if(numeros==56)cout<< numeros<<" = cincuenta y seis"<<endl;
if(numeros==57)cout<< numeros<<" = cincuenta y siete"<<endl;
if(numeros==58)cout<< numeros<<" = cincuenta y ocho"<<endl;
if(numeros==59)cout<< numeros<<" = cincuenta y nueve"<<endl;
if(numeros==60)cout<< numeros<<" = sesenta"<<endl;
if(numeros==61)cout<< numeros<<" = sesenta y uno"<<endl;
if(numeros==62)cout<< numeros<<" = sesenta y dos"<<endl;
if(numeros==63)cout<< numeros<<" = sesenta y tres"<<endl;
if(numeros==64)cout<< numeros<<" = sesenta y cuatro"<<endl;
if(numeros==65)cout<< numeros<<" = sesenta y cinco"<<endl;
if(numeros==66)cout<< numeros<<" = sesenta y  seis"<<endl;
if(numeros==67)cout<< numeros<<" = sesenta y siete"<<endl;
if(numeros==68)cout<< numeros<<" = sesenta y ocho"<<endl;
if(numeros==69)cout<< numeros<<" = sesenta y nueve"<<endl;
if(numeros==70)cout<< numeros<<" = setenta"<<endl;
if(numeros==71)cout<< numeros<<" = setenta y uno"<<endl;
if(numeros==72)cout<< numeros<<" = setenta y dos"<<endl;
if(numeros==73)cout<< numeros<<" =setenta y tres"<<endl;
if(numeros==74)cout<< numeros<<" = setenta y cuatro"<<endl;
if(numeros==75)cout<< numeros<<" =setenta y cinco"<<endl;
if(numeros==76)cout<< numeros<<" =setenta y seis"<<endl;
if(numeros==77)cout<< numeros<<" = setenta y siete"<<endl;
if(numeros==78)cout<< numeros<<" = setenta y ocho"<<endl;
if(numeros==79)cout<< numeros<<" = setenta y nueve"<<endl;
if(numeros==80)cout<< " =ochenta"<<endl;
if(numeros==81)cout<< " =ochenta y uno"<<endl;
if(numeros==82)cout<< " =ochenta y dos"<<endl;
if(numeros==83)cout<<" =ochenta y tres"<<endl;
if(numeros==84)cout<<" =ochenta y cuatro"<<endl;
if(numeros==85)cout<<" =ochenta y cinco"<<endl;
if(numeros==86)cout<<" =ochenta y seis"<<endl;
if(numeros==87)cout<<" =ochenta y siete"<<endl;
if(numeros==88)cout<<" =ochenta y ocho"<<endl;
if(numeros==89)cout<<" =ochenta y nueve"<<endl;
if(numeros==90)cout<<" =noventa"<<endl;
if(numeros==91)cout<<" =noventa y uno"<<endl;
if(numeros==92)cout<<" =noventa y dos"<<endl;
if(numeros==93)cout<<" =noventa y tres"<<endl;
if(numeros==94)cout<<" =noventa y cuatro"<<endl;
if(numeros==95)cout<<" = noventa y cinco"<<endl;
if(numeros==96)cout<<" =noventa y sesis"<<endl;
if(numeros==97)cout<<" =noventa y siete"<<endl;
if(numeros==98)cout<<" =noventa y ocho"<<endl;
if(numeros==99)cout<<" =noventa y nueve"<<endl;
if(numeros==100)cout<<" =cien"<<endl;
if (numeros==101)cout<< numeros<<" = ciento uno"<<endl;
if (numeros==102)cout<< numeros<<" = ciento dos"<<endl;
if(numeros==103)cout<< numeros<<" = ciento tres"<<endl;
if(numeros==104)cout<< numeros<<" = ciento cuatro"<<endl;
if(numeros==105)cout<< numeros<<" = ciento cinco"<<endl;
if(numeros==106)cout<< numeros<<" = ciento seis"<<endl;
if(numeros==107)cout<< numeros<<" = ciento siete"<<endl;
if(numeros==108)cout<< numeros<<" = ciento ocho"<<endl;
if(numeros==109)cout<< numeros<<" = ciento nueve"<<endl;
if(numeros==110)cout<< numeros<<" = ciento diez"<<endl;
if(numeros==111)cout<< numeros<<" = ciento once"<<endl;
if(numeros==112)cout<< numeros<<" = ciento doce"<<endl;
if(numeros==113)cout<< numeros<<" = ciento trece"<<endl;
if(numeros==114)cout<< numeros<<" = ciento catorce"<<endl;
if(numeros==115)cout<< numeros<<" = ciento quice"<<endl;
if(numeros==116)cout<< numeros<<" = ciento dieciseis"<<endl;
if(numeros==117)cout<< numeros<<" = ciento diecisiete"<<endl;
if(numeros==118)cout<< numeros<<" = ciento dieciocho"<<endl;
if(numeros==119)cout<< numeros<<" = ciento diecinueve"<<endl;
if(numeros==120)cout<< numeros<<" = ciento veinte"<<endl;
if(numeros==121)cout<< numeros<<" = ciento veintiuno"<<endl;
if(numeros==122)cout<< numeros<<" = ciento veintidos"<<endl;
if(numeros==123)cout<< numeros<<" = ciento veintitres"<<endl;
if(numeros==124)cout<< numeros<<" = ciento veinticuatro"<<endl;
if(numeros==125)cout<< numeros<<" = ciento veinticinco"<<endl;
if(numeros==126)cout<< numeros<<" = ciento veintiseis"<<endl;
if(numeros==127)cout<< numeros<<" = ciento veintisiete"<<endl;
if(numeros==128)cout<< numeros<<" = ciento veintiocho"<<endl;
if(numeros==129)cout<< numeros<<" = ciento veintinueve"<<endl;
if(numeros==130)cout<< numeros<<" = ciento treinta"<<endl;
if(numeros==131)cout<< numeros<<" = ciento treinta yuno"<<endl;
if(numeros==132)cout<< numeros<<" = ciento treinta y dos"<<endl;
if(numeros==133)cout<< numeros<<" = ciento treinta y tres"<<endl;
if(numeros==134)cout<< numeros<<" = ciento treinta y cuatro"<<endl;
if(numeros==135)cout<< numeros<<" =ciento treinta y cinco"<<endl;
if(numeros==136)cout<< numeros<<" =ciento treinta y seis"<<endl;
if(numeros==137)cout<< numeros<<" = ciento treinta y siete"<<endl;
if(numeros==138)cout<< numeros<<" = ciento treinta y ocho"<<endl;
if(numeros==139)cout<< numeros<<" = ciento treinta y nueve"<<endl;
if(numeros==140)cout<< numeros<<" = ciento cuarenta"<<endl;
if (numeros==141)cout<< numeros<<" = ciento cuarenta y uno"<<endl;
if (numeros==142)cout<< numeros<<" = ciento cuarenta y dos"<<endl;
if(numeros==143)cout<< numeros<<" = ciento cuarenta y tres"<<endl;
if(numeros==144)cout<< numeros<<" = ciento cuarenta y cuatro"<<endl;
if(numeros==145)cout<< numeros<<" = ciento cuarenta y cinco"<<endl;
if(numeros==146)cout<< numeros<<" = ciento cuarentaiseis"<<endl;
if(numeros==147)cout<< numeros<<" = ciento cuarenta y siete"<<endl;
if(numeros==148)cout<< numeros<<" = ciento cuarenta y ocho"<<endl;
if(numeros==149)cout<< numeros<<" = ciento cuarenta y nueve"<<endl;
if(numeros==150)cout<< numeros<<" = ciento cincuenta"<<endl;
if(numeros==151)cout<< numeros<<" = ciento cincuenta y uno"<<endl;
if(numeros==152)cout<< numeros<<" = ciento cincuenta y dos"<<endl;
if(numeros==153)cout<< numeros<<" = ciento cincuenta y tres"<<endl;
if(numeros==154)cout<< numeros<<" = ciento cincuenta y cuatro"<<endl;
if(numeros==155)cout<< numeros<<" =ciento cincuenta y cinco"<<endl;
if(numeros==156)cout<< numeros<<" = ciento cincuenta y seis"<<endl;
if(numeros==157)cout<< numeros<<" = ciento cincuenta y siete"<<endl;
if(numeros==158)cout<< numeros<<" = ciento cincuenta y ocho"<<endl;
if(numeros==159)cout<< numeros<<" = ciento cincuenta y nueve"<<endl;
if(numeros==160)cout<< numeros<<" = ciento sesenta"<<endl;
if(numeros==161)cout<< numeros<<" = ciento sesenta y uno"<<endl;
if(numeros==162)cout<< numeros<<" = ciento sesenta y dos"<<endl;
if(numeros==163)cout<< numeros<<" = ciento sesenta y tres"<<endl;
if(numeros==164)cout<< numeros<<" = ciento sesenta y cuatro"<<endl;
if(numeros==165)cout<< numeros<<" = ciento sesenta y icinco"<<endl;
if(numeros==166)cout<< numeros<<" = ciento sesenta y seis"<<endl;
if(numeros==167)cout<< numeros<<" = ciento sesenta y siete"<<endl;
if(numeros==168)cout<< numeros<<" = ciento sesenta y ocho"<<endl;
if(numeros==169)cout<< numeros<<" = ciento sesenta y nueve"<<endl;
if(numeros==170)cout<< numeros<<" = ciento setenta"<<endl;
if(numeros==171)cout<< numeros<<" = ciento setenta y uno"<<endl;
if(numeros==172)cout<< numeros<<" = ciento ciento setenta y dos"<<endl;
if(numeros==173)cout<< numeros<<" =ciento setenta y tres"<<endl;
if(numeros==174)cout<< numeros<<" = cientoosetenta y cuatro"<<endl;
if(numeros==175)cout<< numeros<<" =ciento setenta y cinco"<<endl;
if(numeros==176)cout<< numeros<<" =ciento setenta y seis"<<endl;
if(numeros==177)cout<< numeros<<" = ciento setenta y siete"<<endl;
if(numeros==178)cout<< numeros<<" = cienton setenta y ocho"<<endl;
if(numeros==179)cout<< numeros<<" = ciento setenta y nueve"<<endl;
if(numeros==180)cout<< " =ciento ochenta"<<endl;
if(numeros==181)cout<< " =ciento ochenta y uno"<<endl;
if(numeros==182)cout<< " =ciento ochenta ydos"<<endl;
if(numeros==183)cout<<" =ciento ochenta y tres"<<endl;
if(numeros==184)cout<<" =ciento ochenta ycuatro"<<endl;
if(numeros==185)cout<<" =ciento ochenta y cinco"<<endl;
if(numeros==186)cout<<" =ciento ochenta y seis"<<endl;
if(numeros==187)cout<<" =ciento ochenta y siete"<<endl;
if(numeros==188)cout<<" =ciento ochenta  y ocho"<<endl;
if(numeros==189)cout<<" =ciento ochenta y nueve"<<endl;
if(numeros==190)cout<<" = ciento noventa"<<endl;
if(numeros==191)cout<<" = ciento noventa y uno"<<endl;
if(numeros==192)cout<<" = ciento noventa y dos"<<endl;
if(numeros==193)cout<<" = ciento noventa y tres"<<endl;
if(numeros==194)cout<<" = ciento noventa y cuatro"<<endl;
if(numeros==195)cout<<" = ciento noventa y cinco"<<endl;
if(numeros==196)cout<<" = ciento noventa y sesis"<<endl;
if(numeros==197)cout<<" = ciento noventa y siete"<<endl;
if(numeros==198)cout<<" =cien nonoventa y ocho"<<endl;
if(numeros==199)cout<<" =ciento noventa y nueve"<<endl;
if(numeros==200)cout<<" =doscientos"<<endl;
if (numeros==201)cout<< numeros<<" = doscientos uno"<<endl;
if (numeros==202)cout<< numeros<<" = doscientos dos"<<endl;
if(numeros==203)cout<< numeros<<" = doscientos tres"<<endl;
if(numeros==204)cout<< numeros<<" = doscientos cuatro"<<endl;
if(numeros==205)cout<< numeros<<" = doscientos cinco"<<endl;
if(numeros==206)cout<< numeros<<" = doscientos seis"<<endl;
if(numeros==207)cout<< numeros<<" = doscientos siete"<<endl;
if(numeros==208)cout<< numeros<<" = doscientos ocho"<<endl;
if(numeros==209)cout<< numeros<<" = doscientos nueve"<<endl;
if(numeros==210)cout<< numeros<<" = doscientos diez"<<endl;
if(numeros==211)cout<< numeros<<" = doscientos once"<<endl;
if(numeros==212)cout<< numeros<<" = doscientos doce"<<endl;
if(numeros==213)cout<< numeros<<" = doscientos trece"<<endl;
if(numeros==214)cout<< numeros<<" = doscientos catorce"<<endl;
if(numeros==215)cout<< numeros<<" = doscientos quice"<<endl;
if(numeros==216)cout<< numeros<<" = doscientos dieciseis"<<endl;
if(numeros==217)cout<< numeros<<" = doscientos diecisiete"<<endl;
if(numeros==218)cout<< numeros<<" = doscientos dieciocho"<<endl;
if(numeros==219)cout<< numeros<<" = doscientosdiecinueve"<<endl;
if(numeros==220)cout<< numeros<<" = doscientos veinte"<<endl;
if(numeros==221)cout<< numeros<<" = doscientos veintiuno"<<endl;
if(numeros==222)cout<< numeros<<" = doscientos veintidos"<<endl;
if(numeros==223)cout<< numeros<<" = doscientos veintitres"<<endl;
if(numeros==224)cout<< numeros<<" = doscientos veinticuatro"<<endl;
if(numeros==225)cout<< numeros<<" = doscientos veinticinco"<<endl;
if(numeros==226)cout<< numeros<<" = doscientos veintiseis"<<endl;
if(numeros==227)cout<< numeros<<" = doscientos veintisiete"<<endl;
if(numeros==228)cout<< numeros<<" = doscientos veintiocho"<<endl;
if(numeros==229)cout<< numeros<<" = doscientos veintinueve"<<endl;
if(numeros==230)cout<< numeros<<" = doscientos treinta"<<endl;
if(numeros==231)cout<< numeros<<" = doscientos treinta y uno"<<endl;
if(numeros==232)cout<< numeros<<" = doscientos treinta y dos"<<endl;
if(numeros==233)cout<< numeros<<" = doscientos treinta y tres"<<endl;
if(numeros==234)cout<< numeros<<" = doscientos treinta y cuatro"<<endl;
if(numeros==235)cout<< numeros<<" =doscientos treinta y cinco"<<endl;
if(numeros==236)cout<< numeros<<" =doscientos treinta y seis"<<endl;
if(numeros==237)cout<< numeros<<" = doscientos treinta y  siete"<<endl;
if(numeros==238)cout<< numeros<<" = doscientos treinta y ocho"<<endl;
if(numeros==239)cout<< numeros<<" = doscientos treinta y nueve"<<endl;
if(numeros==240)cout<< numeros<<" = doscientos cuarenta"<<endl;
if (numeros==241)cout<< numeros<<" = doscientos cuarenta y uno"<<endl;
if (numeros==242)cout<< numeros<<" = doscientos cuarenta y dos"<<endl;
if(numeros==243)cout<< numeros<<" = doscientos cuarenta y tres"<<endl;
if(numeros==244)cout<< numeros<<" = doscientos cuarenta y cuatro"<<endl;
if(numeros==245)cout<< numeros<<" = doscientos cuarenta y cinco"<<endl;
if(numeros==246)cout<< numeros<<" = doscientos cuarenta y seis"<<endl;
if(numeros==247)cout<< numeros<<" = doscientos cuarenta y siete"<<endl;
if(numeros==248)cout<< numeros<<" = doscientos cuarenta y ocho"<<endl;
if(numeros==249)cout<< numeros<<" = doscientos cuarenta y nueve"<<endl;
if(numeros==250)cout<< numeros<<" = doscientos cincuenta"<<endl;
if(numeros==251)cout<< numeros<<" = doscientos cincuenta y uno"<<endl;
if(numeros==252)cout<< numeros<<" = doscientos cincuenta y dos"<<endl;
if(numeros==253)cout<< numeros<<" = doscientos cincuenta y tres"<<endl;
if(numeros==254)cout<< numeros<<" = doscientos cincuenta y cuatro"<<endl;
if(numeros==255)cout<< numeros<<" = doscientos cincuenta y cinco"<<endl;
if(numeros==256)cout<< numeros<<" = doscientos cincuenta y seis"<<endl;
if(numeros==257)cout<< numeros<<" = doscientos cincuenta y siete"<<endl;
if(numeros==258)cout<< numeros<<" = doscientos cincuenta y ocho"<<endl;
if(numeros==259)cout<< numeros<<" =  doscientos cincuenta y nueve"<<endl;
if(numeros==260)cout<< numeros<<" =  doscientos sesenta"<<endl;
if(numeros==261)cout<< numeros<<" =  doscientos sesenta y uno"<<endl;
if(numeros==262)cout<< numeros<<" =  doscientos sesenta y dos"<<endl;
if(numeros==263)cout<< numeros<<" =  doscientos sesenta y tres"<<endl;
if(numeros==264)cout<< numeros<<" =  doscientos sesenta y cuatro"<<endl;
if(numeros==265)cout<< numeros<<" =  doscientos sesenta y cinco"<<endl;
if(numeros==266)cout<< numeros<<" = doscientos sesenta y seis"<<endl;
if(numeros==267)cout<< numeros<<" =  doscientos sesenta y siete"<<endl;
if(numeros==268)cout<< numeros<<" =  doscientos sesenta y ocho"<<endl;
if(numeros==269)cout<< numeros<<" =  doscientos sesenta y nueve"<<endl;
if(numeros==270)cout<< numeros<<" =  doscientos setenta"<<endl;
if(numeros==271)cout<< numeros<<" =  doscientos setenta y uno"<<endl;
if(numeros==272)cout<< numeros<<" =  doscientos setenta y dos"<<endl;
if(numeros==273)cout<< numeros<<" = doscientos setenta y tres"<<endl;
if(numeros==274)cout<< numeros<<" =  doscientos setenta y cuatro"<<endl;
if(numeros==275)cout<< numeros<<" =  doscientos setenta y cinco"<<endl;
if(numeros==276)cout<< numeros<<" =  doscientos setenta y seis"<<endl;
if(numeros==277)cout<< numeros<<" =  doscientos setent y siete"<<endl;
if(numeros==278)cout<< numeros<<" =  doscientos setenta y ocho"<<endl;
if(numeros==279)cout<< numeros<<" =  doscientos setenta y nueve"<<endl;
if(numeros==280)cout<< " = doscientos ochenta"<<endl;
if(numeros==281)cout<< " = doscientos ochenta y uno"<<endl;
if(numeros==282)cout<< " = doscientos ochenta y dos"<<endl;
if(numeros==283)cout<<" = doscientos ochenta y tres"<<endl;
if(numeros==284)cout<<" =  doscientos ochenta y cuatro"<<endl;
if(numeros==285)cout<<" =  doscientos ochenta y cinco"<<endl;
if(numeros==286)cout<<" = doscientos ochenta y seis"<<endl;
if(numeros==287)cout<<" = doscientos ochenta y siete"<<endl;
if(numeros==288)cout<<" = doscientos ochenta y ocho"<<endl;
if(numeros==289)cout<<" = doscientos ochenta y nueve"<<endl;
if(numeros==290)cout<<" = doscientos noventa"<<endl;
if(numeros==291)cout<<" = doscientos noventa y uno"<<endl;
if(numeros==292)cout<<" = doscientos noventa y dos"<<endl;
if(numeros==292)cout<<" = doscientos noventa y dos"<<endl;
if(numeros==293)cout<<" = doscientos noventa y tres"<<endl;
if(numeros==294)cout<<" =noventa y cuatro"<<endl;
if(numeros==295)cout<<" = doscientos noventa y cinco"<<endl;
if(numeros==296)cout<<" =doscientos noventa y sesis"<<endl;
if(numeros==297)cout<<" =doscientos noventa y siete"<<endl;
if(numeros==298)cout<<" =doscientosnoventa y ocho"<<endl;
if(numeros==299)cout<<" =doscientosnoventa y nueve"<<endl;
if(numeros==300)cout<<" =trescientos"<<endl;
if (numeros==301)cout<< numeros<<" = trescientos uno"<<endl;
if (numeros==302)cout<< numeros<<" = trescientos dos"<<endl;
if(numeros==303)cout<< numeros<<" =  trescientos tres"<<endl;
if(numeros==304)cout<< numeros<<" = trescientos cuatro"<<endl;
if(numeros==305)cout<< numeros<<" = trescientos cinco"<<endl;
if(numeros==306)cout<< numeros<<" = trescientos seis"<<endl;
if(numeros==307)cout<< numeros<<" = trescientos siete"<<endl;
if(numeros==308)cout<< numeros<<" = trescientos ocho"<<endl;
if(numeros==309)cout<< numeros<<" = trescientos nueve"<<endl;
if(numeros==310)cout<< numeros<<" = trescientos diez"<<endl;
if(numeros==311)cout<< numeros<<" = trescientos once"<<endl;
if(numeros==312)cout<< numeros<<" = trescientos doce"<<endl;
if(numeros==313)cout<< numeros<<" = trescientos trece"<<endl;
if(numeros==314)cout<< numeros<<" = trescientos catorce"<<endl;
if(numeros==315)cout<< numeros<<" = trescientos quice"<<endl;
if(numeros==316)cout<< numeros<<" = trescientos dieciseis"<<endl;
if(numeros==317)cout<< numeros<<" = trescientos diecisiete"<<endl;
if(numeros==318)cout<< numeros<<" = trescientos dieciocho"<<endl;
if(numeros==319)cout<< numeros<<" = trescientos diecinueve"<<endl;
if(numeros==320)cout<< numeros<<" = trescientos veinte"<<endl;
if(numeros==321)cout<< numeros<<" = trescientos veintiuno"<<endl;
if(numeros==322)cout<< numeros<<" = trescientos veintidos"<<endl;
if(numeros==323)cout<< numeros<<" =  trescientos veintitres"<<endl;
if(numeros==324)cout<< numeros<<" = trescientos veinticuatro"<<endl;
if(numeros==325)cout<< numeros<<" = trescientos veinticinco"<<endl;
if(numeros==326)cout<< numeros<<" = trescientos veintiseis"<<endl;
if(numeros==327)cout<< numeros<<" = trescientos veintisiete"<<endl;
if(numeros==328)cout<< numeros<<" = trescientos veintiocho"<<endl;
if(numeros==329)cout<< numeros<<" = trescientos veintinueve"<<endl;
if(numeros==330)cout<< numeros<<" = trescientos treinta"<<endl;
if(numeros==331)cout<< numeros<<" = trescientos treinta y uno"<<endl;
if(numeros==332)cout<< numeros<<" = trescientos trenta y dos"<<endl;
if(numeros==333)cout<< numeros<<" = trescientos treinta y tres"<<endl;
if(numeros==334)cout<< numeros<<" = trescieento treinta y cuatro"<<endl;
if(numeros==335)cout<< numeros<<" =trescientos treinta y cinco"<<endl;
if(numeros==336)cout<< numeros<<" =trescientos treinta y seis"<<endl;
if(numeros==337)cout<< numeros<<" = trescientos treinta y siete"<<endl;
if(numeros==338)cout<< numeros<<" = trescientos treinta y ocho"<<endl;
if(numeros==339)cout<< numeros<<" = trescientos treinta y nueve"<<endl;
if(numeros==340)cout<< numeros<<" = trescientos cuarenta"<<endl;
if (numeros==341)cout<< numeros<<" = trescientos cuarenta y uno"<<endl;
if (numeros==342)cout<< numeros<<" = trescientos cuarenta y dos"<<endl;
if(numeros==343)cout<< numeros<<" = trescientos cuarenta y tres"<<endl;
if(numeros==344)cout<< numeros<<" = trescientos cuarenta y cuatro"<<endl;
if(numeros==345)cout<< numeros<<" = trescientos cuarenta y cinco"<<endl;
if(numeros==346)cout<< numeros<<" = trescientos cuarenta y seis"<<endl;
if(numeros==347)cout<< numeros<<" = trescientos cuarenta y siete"<<endl;
if(numeros==348)cout<< numeros<<" = trescientos cuarenta y ocho"<<endl;
if(numeros==349)cout<< numeros<<" = trescientos cuarenta y nueve"<<endl;
if(numeros==350)cout<< numeros<<" = trescientos cincuenta"<<endl;
if(numeros==351)cout<< numeros<<" = trescientos cincuenta y uno"<<endl;
if(numeros==352)cout<< numeros<<" = trescientoscincuenta y dos"<<endl;
if(numeros==353)cout<< numeros<<" = trescientos cincuenta y tres"<<endl;
if(numeros==354)cout<< numeros<<" = trescientos cincuenta y cuatro"<<endl;
if(numeros==355)cout<< numeros<<" = trescientos cincuenta y cinco"<<endl;
if(numeros==356)cout<< numeros<<" = trescientos cincuenta y seis"<<endl;
if(numeros==357)cout<< numeros<<" = trescientos cincuenta y siete"<<endl;
if(numeros==358)cout<< numeros<<" = trescientos cincuenta y ocho"<<endl;
if(numeros==359)cout<< numeros<<" = trescientos cincuenta y nueve"<<endl;
if(numeros==360)cout<< numeros<<" = trescientos sesenta"<<endl;
if(numeros==361)cout<< numeros<<" = trescientos sesenta y uno"<<endl;
if(numeros==362)cout<< numeros<<" = trescientos sesenta y dos"<<endl;
if(numeros==363)cout<< numeros<<" = trescientos sesenta y tres"<<endl;
if(numeros==364)cout<< numeros<<" = trescientos sesenta y cuatro"<<endl;
if(numeros==365)cout<< numeros<<" = trescientos sesenta y cinco"<<endl;
if(numeros==366)cout<< numeros<<" = trescientos sesenta y seis"<<endl;
if(numeros==367)cout<< numeros<<" = trescientos sesenta y siete"<<endl;
if(numeros==368)cout<< numeros<<" = trescientos sesenta y ocho"<<endl;
if(numeros==369)cout<< numeros<<" = trescientos sesenta y nueve"<<endl;
if(numeros==370)cout<< numeros<<" = trescientos setenta"<<endl;
if(numeros==371)cout<< numeros<<" = trescientos setenta y uno"<<endl;
if(numeros==372)cout<< numeros<<" = trescientos setenta y dos"<<endl;
if(numeros==373)cout<< numeros<<" =trescientos setenta y tres"<<endl;
if(numeros==374)cout<< numeros<<" = trescientos setenta y cuatro"<<endl;
if(numeros==375)cout<< numeros<<" = trescientos setenta y cinco"<<endl;
if(numeros==376)cout<< numeros<<" =trescientos setenta y seis"<<endl;
if(numeros==377)cout<< numeros<<" = trescientos setenta y siete"<<endl;
if(numeros==378)cout<< numeros<<" = trescientos setenta y ocho"<<endl;
if(numeros==379)cout<< numeros<<" = trescientos setenta y nueve"<<endl;
if(numeros==380)cout<< " =trescientos ochenta"<<endl;
if(numeros==381)cout<< " =trescientos ochenta y uno"<<endl;
if(numeros==382)cout<< " =trescientos ochenta y dos"<<endl;
if(numeros==383)cout<<" =trescientos ochenta y tres "<<endl;
if(numeros==384)cout<<" =trescientos ochenta y cuatro  "<<endl;
if(numeros==385)cout<<" = trescientos ochenta y cinco"<<endl;
if(numeros==386)cout<<" =tres cientos ochenta y seis "<<endl;
if(numeros==387)cout<<" =trescientos ochenta y siete"<<endl;
if(numeros==388)cout<<" = trescientos ochenta y ocho"<<endl;
if(numeros==389)cout<<" = trescientos ochenta y nueve"<<endl;
if(numeros==390)cout<<" =  trescientos onoventa"<<endl;
if(numeros==91)cout<<" = trescientos noventa y uno "<<endl;
if(numeros==392)cout<<" = trescientos noventa y dos "<<endl;
if(numeros==393)cout<<" = trescientos noventa y tres "<<endl;
if(numeros==394)cout<<" = trescientos noventa y tres"<<endl;
if(numeros==395)cout<<" = trescientos noventa y cuatro "<<endl;
if(numeros==396)cout<<" = trescientos noventa y cinco "<<endl;
if(numeros==397)cout<<" = trescientos noventa y seis"<<endl;
if(numeros==398)cout<<" =tresientos noventa y ocho "<<endl;
if(numeros==399)cout<<" =tresientos noventa y nueve"<<endl;
if(numeros==400)cout<<" =cuatrocientos "<<endl;
if (numeros==401)cout<< numeros<<" = cuatrocientos uno"<<endl;
if (numeros==402)cout<< numeros<<" =cuatrocientos dos"<<endl;
if(numeros==403)cout<< numeros<<" =cuatrocientos tres"<<endl;
if(numeros==404)cout<< numeros<<" =cuatrocientos cuatro"<<endl;
if(numeros==405)cout<< numeros<<" =cuatrocientos cinco"<<endl;
if(numeros==406)cout<< numeros<<" =cuatrocientos seis"<<endl;
if(numeros==407)cout<< numeros<<" =cuatrocientos siete"<<endl;
if(numeros==408)cout<< numeros<<" =cuatrocientos ocho"<<endl;
if(numeros==409)cout<< numeros<<" =cuatrocientos nueve"<<endl;
if(numeros==410)cout<< numeros<<" = cuatrocientos diez"<<endl;
if(numeros==411)cout<< numeros<<" = cuatrocientos once"<<endl;
if(numeros==412)cout<< numeros<<" = cuatrocientos doce"<<endl;
if(numeros==413)cout<< numeros<<" = cuatrocientos trece"<<endl;
if(numeros==414)cout<< numeros<<" = cuatrocientos catorce"<<endl;
if(numeros==415)cout<< numeros<<" = cuatrocientos quice"<<endl;
if(numeros==416)cout<< numeros<<" = cuatrocientos dieciseis"<<endl;
if(numeros==417)cout<< numeros<<" = cuatrocientos diecisiete"<<endl;
if(numeros==418)cout<< numeros<<" = cuatrocientos dieciocho"<<endl;
if(numeros==419)cout<< numeros<<" = cuatrocientos diecinueve"<<endl;
if(numeros==420)cout<< numeros<<" = cuatrocientos veinte"<<endl;
if(numeros==421)cout<< numeros<<" = cuatrocientos veintiuno"<<endl;
if(numeros==422)cout<< numeros<<" = cuatrocientos veintidos"<<endl;
if(numeros==423)cout<< numeros<<" = cuatrocientos veintitres"<<endl;
if(numeros==424)cout<< numeros<<" = cuatrocientos veinticuatro"<<endl;
if(numeros==425)cout<< numeros<<" =  cuatrocientos veinticinco"<<endl;
if(numeros==426)cout<< numeros<<" = cuatrocientos veintiseis"<<endl;
if(numeros==427)cout<< numeros<<" = cuatrocientos veintisiete"<<endl;
if(numeros==428)cout<< numeros<<" = cuatrocientos veintiocho"<<endl;
if(numeros==429)cout<< numeros<<" = cuatrocientos veintinueve"<<endl;
if(numeros==430)cout<< numeros<<" = cuatrocientos treinta"<<endl;
if(numeros==431)cout<< numeros<<" = cuatrocientos treinta y uno"<<endl;
if(numeros==432)cout<< numeros<<" = cuatrocientos treinta y dos"<<endl;
if(numeros==433)cout<< numeros<<" = cuatrocientos treinta y tres"<<endl;
if(numeros==434)cout<< numeros<<" = cuatrocientos treinta y cuatro"<<endl;
if(numeros==435)cout<< numeros<<" = cuatrocientos treinta y cinco"<<endl;
if(numeros==436)cout<< numeros<<" = cuatrocientos treinta y seis"<<endl;
if(numeros==437)cout<< numeros<<" = cuatrocientos treinta y siete"<<endl;
if(numeros==438)cout<< numeros<<" = cuatrocientos treinta y ocho"<<endl;
if(numeros==439)cout<< numeros<<" = cuatrocientos treinta y nueve"<<endl;
if(numeros==440)cout<< numeros<<" = cuatrocientos cuarenta"<<endl;
if (numeros==441)cout<< numeros<<" = cuatrocientos cuarenta y uno"<<endl;
if (numeros==442)cout<< numeros<<" = cuatrocientos cuarenta y dos"<<endl;
if(numeros==443)cout<< numeros<<" = cuatrocientos cuarenta y tres"<<endl;
if(numeros==444)cout<< numeros<<" = cuatrocientos cuarenta y cuatro"<<endl;
if(numeros==445)cout<< numeros<<" = cuatrocientos cuarenta y cinco"<<endl;
if(numeros==446)cout<< numeros<<" = cuatrocientos cuarenta y seis"<<endl;
if(numeros==447)cout<< numeros<<" = cuatrocientos cuarenta y siete"<<endl;
if(numeros==448)cout<< numeros<<" = cuatrocientos cuarenta y ocho"<<endl;
if(numeros==449)cout<< numeros<<" = cuatrocientos cuarenta y nueve"<<endl;
if(numeros==450)cout<< numeros<<" = cuatrocientos cincuenta"<<endl;
if(numeros==451)cout<< numeros<<" = cuatrocientos cincuenta y uno"<<endl;
if(numeros==452)cout<< numeros<<" = cuatrocientos cincuenta y dos"<<endl;
if(numeros==453)cout<< numeros<<" = cuatrocientos cincuenta y tres"<<endl;
if(numeros==454)cout<< numeros<<" = cuatrocientos cincuenta y cuatro"<<endl;
if(numeros==455)cout<< numeros<<" = cuatrocientos cincuenta y cinco"<<endl;
if(numeros==456)cout<< numeros<<" = cuatrocientos cincuenta y seis"<<endl;
if(numeros==457)cout<< numeros<<" = cuatrocientos cincuenta y siete"<<endl;
if(numeros==458)cout<< numeros<<" = cuatrocientos cincuenta y ocho"<<endl;
if(numeros==459)cout<< numeros<<" = cuatrocientos cincuenta y nueve"<<endl;
if(numeros==460)cout<< numeros<<" = cuatrocientos sesenta"<<endl;
if(numeros==461)cout<< numeros<<" = cuatrocientos sesenta y uno"<<endl;
if(numeros==462)cout<< numeros<<" = cuatrocientos sesenta y dos"<<endl;
if(numeros==463)cout<< numeros<<" = cuatrocientos sesenta y tres"<<endl;
if(numeros==464)cout<< numeros<<" = cuatrocientos sesenta y cuatro"<<endl;
if(numeros==465)cout<< numeros<<" = cuatrocientos sesenta y cinco"<<endl;
if(numeros==466)cout<< numeros<<" = cuatrocientos sesenta y seis"<<endl;
if(numeros==467)cout<< numeros<<" = cuatrocientos sesenta y siete"<<endl;
if(numeros==468)cout<< numeros<<" = cuatrocientos sesenta y ocho"<<endl;
if(numeros==469)cout<< numeros<<" = cuatrocientos sesenta y nueve"<<endl;
if(numeros==470)cout<< numeros<<" = cuatrocientos setenta"<<endl;
if(numeros==471)cout<< numeros<<" = cuatrocientos setenta y uno"<<endl;
if(numeros==472)cout<< numeros<<" = cuatrocientos setenta y dos"<<endl;
if(numeros==473)cout<< numeros<<" = cuatrocientossetenta y tres"<<endl;
if(numeros==474)cout<< numeros<<" = cuatrocientos setenta y cuatro"<<endl;
if(numeros==475)cout<< numeros<<" = cuatrocientos setenta y cinco"<<endl;
if(numeros==476)cout<< numeros<<" = cuatrocientos setenta y seis"<<endl;
if(numeros==477)cout<< numeros<<" = cuatrocientos setenta y siete"<<endl;
if(numeros==478)cout<< numeros<<" = cuatrocientos setenta y ocho"<<endl;
if(numeros==479)cout<< numeros<<" = cuatrocientos setenta y nueve"<<endl;
if(numeros==480)cout<< " = cuatrocientos ochenta"<<endl;
if(numeros==481)cout<< " = cuatrocientosochenta y uno"<<endl;
if(numeros==482)cout<< " =cuatrocientos ochenta y dos"<<endl;
if(numeros==483)cout<<" = cuatrocientos ochenta y tres"<<endl;
if(numeros==484)cout<<" = cuatrocientos ochenta y cuatro"<<endl;
if(numeros==485)cout<<" = cuatrocientos ochenta y cinco"<<endl;
if(numeros==486)cout<<" = cuatrocientos ochenta y seis"<<endl;
if(numeros==487)cout<<" = cuatrocientos ochenta y siete"<<endl;
if(numeros==488)cout<<" = cuatrocientos ochenta y ocho"<<endl;
if(numeros==489)cout<<" = cuatrocientos ochenta y nueve"<<endl;
if(numeros==490)cout<<" = cuatrocientos noventa"<<endl;
if(numeros==491)cout<<" = cuatrocientos noventa y uno"<<endl;
if(numeros==492)cout<<" = cuatrocientos noventa y dos"<<endl;
if(numeros==493)cout<<" =cuatrocientos noventa y tres"<<endl;
if(numeros==494)cout<<" = cuatrocientos noventa y cuatro"<<endl;
if(numeros==495)cout<<" = cuatrocientos noventa y cinco"<<endl;
if(numeros==496)cout<<" = cuatrocientosnoventa y sesis"<<endl;
if(numeros==497)cout<<" = cuatrocientos noventa y siete"<<endl;
if(numeros==498)cout<<" = cuatrocientos noventa y ocho"<<endl;
if(numeros==499)cout<<" =cuatrocientos noventa y nueve"<<endl;
if(numeros==500)cout<<" =quinientos "<<endl;
if (numeros==501)cout<< numeros<<" =quinientos uno "<<endl;
if (numeros==502)cout<< numeros<<" = quinientos dos "<<endl;
if(numeros==503)cout<< numeros<<" = quinientos tres"<<endl;
if(numeros==504)cout<< numeros<<" =quinientos cuatro"<<endl;
if(numeros==505)cout<< numeros<<" = quinientos cinco"<<endl;
if(numeros==506)cout<< numeros<<" =  quinientos seis"<<endl;
if(numeros==507)cout<< numeros<<" =  quinientos siete"<<endl;
if(numeros==508)cout<< numeros<<" =  quinientos ocho"<<endl;
if(numeros==509)cout<< numeros<<" =  quinientos nueve"<<endl;
if(numeros==510)cout<< numeros<<" =  quinientos diez"<<endl;
if(numeros==511)cout<< numeros<<" =  quinientos once"<<endl;
if(numeros==512)cout<< numeros<<" =  quinientos doce"<<endl;
if(numeros==513)cout<< numeros<<" =  quinientos trece"<<endl;
if(numeros==514)cout<< numeros<<" =  quinientos catorce"<<endl;
if(numeros==515)cout<< numeros<<" =  quinientos toquice"<<endl;
if(numeros==516)cout<< numeros<<" =  quinientos dieciseis"<<endl;
if(numeros==517)cout<< numeros<<" =  quinientos diecisiete"<<endl;
if(numeros==518)cout<< numeros<<" = quinientos dieciocho"<<endl;
if(numeros==519)cout<< numeros<<" = quinientos diecinueve"<<endl;
if(numeros==520)cout<< numeros<<" = quinientosveinte"<<endl;
if(numeros==521)cout<< numeros<<" = quinientos veintiuno"<<endl;
if(numeros==522)cout<< numeros<<" = quinientos veintidos"<<endl;
if(numeros==523)cout<< numeros<<" =  quinientos veintitres"<<endl;
if(numeros==524)cout<< numeros<<" =  quinientos veinticuatro"<<endl;
if(numeros==525)cout<< numeros<<" = quinientos veinticinco"<<endl;
if(numeros==526)cout<< numeros<<" =quinientos veintiseis"<<endl;
if(numeros==527)cout<< numeros<<" = quinientos veintisiete"<<endl;
if(numeros==528)cout<< numeros<<" = quinientos veintiocho"<<endl;
if(numeros==529)cout<< numeros<<" = quinientos veintinueve"<<endl;
if(numeros==530)cout<< numeros<<" =  quinientos treinta"<<endl;
if(numeros==531)cout<< numeros<<" =  quinientos treinta y uno"<<endl;
if(numeros==532)cout<< numeros<<" =  quinientos treintay dos"<<endl;
if(numeros==533)cout<< numeros<<" =  quinientos treinta y tres"<<endl;
if(numeros==534)cout<< numeros<<" =  quinientos treinta y cuatro"<<endl;
if(numeros==535)cout<< numeros<<" = quinientos treinta y cinco"<<endl;
if(numeros==536)cout<< numeros<<" = quinientos treinta y seis"<<endl;
if(numeros==537)cout<< numeros<<" = quinientos treinta y siete"<<endl;
if(numeros==538)cout<< numeros<<" = quinientos treinta y ocho"<<endl;
if(numeros==539)cout<< numeros<<" = quinientos treinta y nueve"<<endl;
if(numeros==540)cout<< numeros<<" = quinientos cuarenta"<<endl;
if (numeros==541)cout<< numeros<<" = quinientos cuarenta y uno"<<endl;
if (numeros==542)cout<< numeros<<" = quinientos cuarenta y dos"<<endl;
if(numeros==543)cout<< numeros<<" = quinientos cuarenta y tres"<<endl;
if(numeros==544)cout<< numeros<<" = quinientos cuarenta y cuatro"<<endl;
if(numeros==545)cout<< numeros<<" = quinientos cuarenta y cinco"<<endl;
if(numeros==546)cout<< numeros<<" = quinientos cuarenta y seis"<<endl;
if(numeros==547)cout<< numeros<<" = quinientos cuarenta y siete"<<endl;
if(numeros==548)cout<< numeros<<" = quinientos cuarenta y ocho"<<endl;
if(numeros==549)cout<< numeros<<" = quinientos cuarenta y nueve"<<endl;
if(numeros==550)cout<< numeros<<" = quinientos cincuenta"<<endl;
if(numeros==551)cout<< numeros<<" = quinientos cincuenta y uno"<<endl;
if(numeros==552)cout<< numeros<<" = quinientos cincuenta y dos"<<endl;
if(numeros==553)cout<< numeros<<" = quinientos cincuenta y tres"<<endl;
if(numeros==554)cout<< numeros<<" = quinientos cincuenta y cuatro"<<endl;
if(numeros==555)cout<< numeros<<" = quinientos cincuenta y cinco"<<endl;
if(numeros==556)cout<< numeros<<" = quinientos cincuenta y seis"<<endl;
if(numeros==557)cout<< numeros<<" = quinientos cuenta y siete"<<endl;
if(numeros==558)cout<< numeros<<" = quinientos cincuenta y ocho"<<endl;
if(numeros==559)cout<< numeros<<" = quinientos cincuenta y neve"<<endl;
if(numeros==560)cout<< numeros<<" = quinientos sesenta"<<endl;
if(numeros==561)cout<< numeros<<" = quinientos sesenta y uno"<<endl;
if(numeros==562)cout<< numeros<<" = quinientos sesenta y dos"<<endl;
if(numeros==563)cout<< numeros<<" = quinientossesenta y tres"<<endl;
if(numeros==564)cout<< numeros<<" = quinientos sesenta y cuatro"<<endl;
if(numeros==565)cout<< numeros<<" =  quinientos sesenta y cinco"<<endl;
if(numeros==566)cout<< numeros<<" = quinientos sesenta y sesis "<<endl;
if(numeros==567)cout<< numeros<<" = quinientos sesenta y siete "<<endl;
if(numeros==568)cout<< numeros<<" = quinientos sesenta y ocho"<<endl;
if(numeros==569)cout<< numeros<<" = quinientos sesenta y nueve"<<endl;
if(numeros==570)cout<< numeros<<" =  quinientos setenta"<<endl;
if(numeros==571)cout<< numeros<<" = quinientos setenta y uno"<<endl;
if(numeros==572)cout<< numeros<<" =  quinientos setenta y dos"<<endl;
if(numeros==573)cout<< numeros<<" = quinientos setenta y tres"<<endl;
if(numeros==574)cout<< numeros<<" = quinientos setenta y cuatro"<<endl;
if(numeros==575)cout<< numeros<<" = quinientos setenta y cinco"<<endl;
if(numeros==576)cout<< numeros<<" =quinientos setenta y seis"<<endl;
if(numeros==577)cout<< numeros<<" = quinientos setenta y siete"<<endl;
if(numeros==578)cout<< numeros<<" = quinientos setenta y ocho"<<endl;
if(numeros==579)cout<< numeros<<" = quinientos setenta y nueve"<<endl;
if(numeros==580)cout<< " = quinientos ochenta"<<endl;
if(numeros==581)cout<< " = quinientos ochenta y uno"<<endl;
if(numeros==582)cout<< " = quinientos ochenta y dos"<<endl;
if(numeros==583)cout<<" = quinientos ochenta y tres"<<endl;
if(numeros==584)cout<<" =quinientos ochenta y cuatro"<<endl;
if(numeros==585)cout<<" =quinientos ochenta y cinco"<<endl;
if(numeros==586)cout<<" =quinientos ochenta y seis"<<endl;
if(numeros==587)cout<<" =quinientos ochenta y siete"<<endl;
if(numeros==588)cout<<" = quinientos ochenta y ocho"<<endl;
if(numeros==589)cout<<" = quinientos noochenta y nueve"<<endl;
if(numeros==590)cout<<" = quinientos noventa"<<endl;
if(numeros==591)cout<<" = quinientos nonoventa y uno"<<endl;
if(numeros==592)cout<<" = quinientos nonoventa y dos"<<endl;
if(numeros==593)cout<<" = quinientos noventa y tres"<<endl;
if(numeros==594)cout<<" = quinientos noventa y cuatro"<<endl;
if(numeros==595)cout<<" = quinientos nonoventa y cinco"<<endl;
if(numeros==596)cout<<" = quinientos noventa y sesis"<<endl;
if(numeros==597)cout<<" = quinientos noventa y siete"<<endl;
if(numeros==598)cout<<" = quinientos noventa y ocho"<<endl;
if(numeros==599)cout<<" = quinientos noventa y nueve"<<endl;
if(numeros==600)cout<<" =seiscientos"<<endl;
if (numeros==601)cout<< numeros<<" = seiscientos uno"<<endl;
if (numeros==602)cout<< numeros<<" = seiscientos dos"<<endl;
if(numeros==603)cout<< numeros<<" = seiscientos tres"<<endl;
if(numeros==604)cout<< numeros<<" = seiscientos cuatro"<<endl;
if(numeros==605)cout<< numeros<<" = seiscientos cinco"<<endl;
if(numeros==606)cout<< numeros<<" = seiscientos seis"<<endl;
if(numeros==607)cout<< numeros<<" = seiscientos siete"<<endl;
if(numeros==608)cout<< numeros<<" = seiscientos ocho"<<endl;
if(numeros==609)cout<< numeros<<" = seiscientos nueve"<<endl;
if(numeros==610)cout<< numeros<<" = seiscientos diez"<<endl;
if(numeros==611)cout<< numeros<<" = seiscientos once"<<endl;
if(numeros==612)cout<< numeros<<" = seiscientos doce"<<endl;
if(numeros==613)cout<< numeros<<" = seiscientos trece"<<endl;
if(numeros==614)cout<< numeros<<" = seiscientos catorce"<<endl;
if(numeros==615)cout<< numeros<<" = seiscientos quice"<<endl;
if(numeros==616)cout<< numeros<<" = seiscientos dieciseis"<<endl;
if(numeros==617)cout<< numeros<<" = seiscientos diecisiete"<<endl;
if(numeros==618)cout<< numeros<<" = seiscientos dieciocho"<<endl;
if(numeros==619)cout<< numeros<<" = seiscientos diecinueve"<<endl;
if(numeros==620)cout<< numeros<<" = seiscientos veinte"<<endl;
if(numeros==621)cout<< numeros<<" = seiscientos veintiuno"<<endl;
if(numeros==622)cout<< numeros<<" = seiscientos veintidos"<<endl;
if(numeros==623)cout<< numeros<<" = seiscientos veintitres"<<endl;
if(numeros==624)cout<< numeros<<" = seiscientos veinticuatro"<<endl;
if(numeros==625)cout<< numeros<<" = seiscientos veinticinco"<<endl;
if(numeros==626)cout<< numeros<<" = seiscientos veintiseis"<<endl;
if(numeros==627)cout<< numeros<<" = seiscientos veintisiete"<<endl;
if(numeros==628)cout<< numeros<<" = seiscientos veintiocho"<<endl;
if(numeros==629)cout<< numeros<<" = seiscientos veintinueve"<<endl;
if(numeros==630)cout<< numeros<<" = seiscientos treinta"<<endl;
if(numeros==631)cout<< numeros<<" = seiscientos treinta y uno"<<endl;
if(numeros==632)cout<< numeros<<" = seiscientos treinta y dos"<<endl;
if(numeros==633)cout<< numeros<<" = seiscientos treinta y tres"<<endl;
if(numeros==634)cout<< numeros<<" = seiscientos treinta y cuatro"<<endl;
if(numeros==635)cout<< numeros<<" = seiscientos treinta y cinco"<<endl;
if(numeros==636)cout<< numeros<<" = seiscientos treinta y seis"<<endl;
if(numeros==637)cout<< numeros<<" = seiscientos treinta y siete"<<endl;
if(numeros==638)cout<< numeros<<" = seiscientos treinta y ocho"<<endl;
if(numeros==639)cout<< numeros<<" = seiscientos treinta y nueve"<<endl;
if(numeros==640)cout<< numeros<<" =  seiscientos cuarenta"<<endl;
if (numeros==641)cout<< numeros<<" = seiscientos cuarenta y uno"<<endl;
if (numeros==642)cout<< numeros<<" = seiscientos cuarenta y dos"<<endl;
if(numeros==643)cout<< numeros<<" = seiscientos cuarenta y tres"<<endl;
if(numeros==644)cout<< numeros<<" = seiscientos cuarenta y cuatro"<<endl;
if(numeros==645)cout<< numeros<<" = seiscientos cuarenta y cinco"<<endl;
if(numeros==646)cout<< numeros<<" = seiscientos cuarenta y seis"<<endl;
if(numeros==647)cout<< numeros<<" = seiscientos cuarenta y siete"<<endl;
if(numeros==648)cout<< numeros<<" = seiscientos cuarenta y ocho"<<endl;
if(numeros==649)cout<< numeros<<" = seiscientos cuarenta y nueve"<<endl;
if(numeros==650)cout<< numeros<<" = seiscientos cincuenta"<<endl;
if(numeros==651)cout<< numeros<<" = seiscientos cincuenta y uno"<<endl;
if(numeros==652)cout<< numeros<<" = seiscientos cincuenta y dos"<<endl;
if(numeros==653)cout<< numeros<<" = seiscientos cincuenta y tres"<<endl;
if(numeros==654)cout<< numeros<<" = seiscientos cincuenta y cuatro"<<endl;
if(numeros==655)cout<< numeros<<" = seiscientos cincuenta y cinco"<<endl;
if(numeros==656)cout<< numeros<<" = seiscientos cincuenta y seis"<<endl;
if(numeros==657)cout<< numeros<<" = seiscientos cincuenta y siete"<<endl;
if(numeros==658)cout<< numeros<<" = seiscientos cincuenta y ocho"<<endl;
if(numeros==659)cout<< numeros<<" = seiscientos cincuenta y neve"<<endl;
if(numeros==660)cout<< numeros<<" = seiscientos sesenta"<<endl;
if(numeros==661)cout<< numeros<<" = seiscientos sesenta y uno"<<endl;
if(numeros==662)cout<< numeros<<" = seiscientos sesenta y dos"<<endl;
if(numeros==663)cout<< numeros<<" = seiscientos sesenta y tres"<<endl;
if(numeros==664)cout<< numeros<<" = seiscientos sesenta y cuatro"<<endl;
if(numeros==665)cout<< numeros<<" = seiscientos sesenta y cinco"<<endl;
if(numeros==666)cout<< numeros<<" = seiscientos sesenta y seis"<<endl;
if(numeros==667)cout<< numeros<<" = seiscientos sesenta y siete"<<endl;
if(numeros==668)cout<< numeros<<" = seiscientos sesenta y ocho"<<endl;
if(numeros==669)cout<< numeros<<" = seiscientos sesenta y nueve"<<endl;
if(numeros==670)cout<< numeros<<" = seiscientos setenta"<<endl;
if(numeros==671)cout<< numeros<<" = seiscientos setenta y uno"<<endl;
if(numeros==672)cout<< numeros<<" = seiscientos setenta y dos"<<endl;
if(numeros==673)cout<< numeros<<" = seiscientos setenta y tres"<<endl;
if(numeros==674)cout<< numeros<<" = seiscientos setenta y cuatro"<<endl;
if(numeros==675)cout<< numeros<<" =seiscientos setenta y cinco"<<endl;
if(numeros==676)cout<< numeros<<" =seiscientos setenta y seis"<<endl;
if(numeros==677)cout<< numeros<<" = seiscientos setenta y siete"<<endl;
if(numeros==678)cout<< numeros<<" = seiscientos setenta y ocho"<<endl;
if(numeros==679)cout<< numeros<<" = seiscientos setenta y nueve"<<endl;
if(numeros==680)cout<< " = seiscientos ochenta"<<endl;
if(numeros==681)cout<< " = seiscientos ochenta y uno"<<endl;
if(numeros==682)cout<< " = seiscientos ochenta y dos"<<endl;
if(numeros==683)cout<<" = seiscientos ochenta y tres"<<endl;
if(numeros==684)cout<<" = seiscientos ochenta y cuatro"<<endl;
if(numeros==685)cout<<" = seiscientos ochenta y cinco"<<endl;
if(numeros==686)cout<<" = seiscientos ochenta y seis"<<endl;
if(numeros==687)cout<<" =seiscientos ochenta y siete"<<endl;
if(numeros==688)cout<<" = seiscientos ochenta y ocho"<<endl;
if(numeros==689)cout<<" =seiscientos ochenta y nueve"<<endl;
if(numeros==690)cout<<" =seiscientos noventa"<<endl;
if(numeros==691)cout<<" =seiscientos noventa y uno"<<endl;
if(numeros==692)cout<<" = seiscientos noventa y dos"<<endl;
if(numeros==693)cout<<" = seiscientos noventa y tres"<<endl;
if(numeros==694)cout<<" =seiscientos noventa y cuatro"<<endl;
if(numeros==695)cout<<" = seiscientos noventa y cinco"<<endl;
if(numeros==696)cout<<" =seiscientos noventa y sesis"<<endl;
if(numeros==697)cout<<" = seiscientos noventa y siete"<<endl;
if(numeros==698)cout<<" =seiscientos noventa y ocho"<<endl;
if(numeros==699)cout<<" =seiscientos noventa y nueve"<<endl;
if(numeros==700)cout<<" =setecientos "<<endl;
if (numeros==701)cout<< numeros<<" = stecientos uno "<<endl;
if (numeros==702)cout<< numeros<<" =setecientos dos"<<endl;
if(numeros==703)cout<< numeros<<" = stecientos tres"<<endl;
if(numeros==704)cout<< numeros<<" = seiscientos cuatro"<<endl;
if(numeros==705)cout<< numeros<<" = seiscientos cinco"<<endl;
if(numeros==706)cout<< numeros<<" = seiscientos seis"<<endl;
if(numeros==707)cout<< numeros<<" = seiscientossiete"<<endl;
if(numeros==708)cout<< numeros<<" = seiscientos ocho"<<endl;
if(numeros==709)cout<< numeros<<" = seiscientos nueve"<<endl;
if(numeros==710)cout<< numeros<<" = setecientos diez"<<endl;
if(numeros==711)cout<< numeros<<" = setecientos once"<<endl;
if(numeros==712)cout<< numeros<<" = setecientos doce"<<endl;
if(numeros==713)cout<< numeros<<" = setecientos trece"<<endl;
if(numeros==714)cout<< numeros<<" = setecientos catorce"<<endl;
if(numeros==715)cout<< numeros<<" = setecientos quice"<<endl;
if(numeros==716)cout<< numeros<<" = setecientos dieciseis"<<endl;
if(numeros==717)cout<< numeros<<" = setecientos diecisiete"<<endl;
if(numeros==718)cout<< numeros<<" =setecientos dieciocho"<<endl;
if(numeros==719)cout<< numeros<<" = setecientos diecinueve"<<endl;
if(numeros==720)cout<< numeros<<" = setecientos veinte"<<endl;
if(numeros==721)cout<< numeros<<" = setecientos veintiuno"<<endl;
if(numeros==722)cout<< numeros<<" = vveintidos"<<endl;
if(numeros==723)cout<< numeros<<" = setecientos veintitres"<<endl;
if(numeros==724)cout<< numeros<<" = setecientos veinticuatro"<<endl;
if(numeros==725)cout<< numeros<<" = setecientos veinticinco"<<endl;
if(numeros==726)cout<< numeros<<" = setecientos veintiseis"<<endl;
if(numeros==727)cout<< numeros<<" = setecientos veintisiete"<<endl;
if(numeros==728)cout<< numeros<<" = setecientos veintiocho"<<endl;
if(numeros==729)cout<< numeros<<" = setecientos veintinueve"<<endl;
if(numeros==730)cout<< numeros<<" = setecientos treinta"<<endl;
if(numeros==731)cout<< numeros<<" = setecientos treinta y uno"<<endl;
if(numeros==732)cout<< numeros<<" = setecientos treinta y dos"<<endl;
if(numeros==733)cout<< numeros<<" = setecientos treinta y tres"<<endl;
if(numeros==734)cout<< numeros<<" = setecientos treinta y cuatro"<<endl;
if(numeros==735)cout<< numeros<<" =setecientos treinta y cinco"<<endl;
if(numeros==736)cout<< numeros<<" =setecientos treinta y seis"<<endl;
if(numeros==737)cout<< numeros<<" =setecientos treinta y siete"<<endl;
if(numeros==738)cout<< numeros<<" = setecientos treinta y ocho"<<endl;
if(numeros==739)cout<< numeros<<" = setecientos treinta y nueve"<<endl;
if(numeros==740)cout<< numeros<<" = setecientos cuarenta"<<endl;
if (numeros==741)cout<< numeros<<" = setecientos cuarenta y uno"<<endl;
if (numeros==742)cout<< numeros<<" = setecientos cuarenta y dos"<<endl;
if(numeros==743)cout<< numeros<<" = setecientos cuarenta y tres"<<endl;
if(numeros==744)cout<< numeros<<" = setecientos cuarenta y cuatro"<<endl;
if(numeros==745)cout<< numeros<<" = setecientos cuarenta y cinco"<<endl;
if(numeros==746)cout<< numeros<<" = setecientos cuarenta y seis"<<endl;
if(numeros==747)cout<< numeros<<" = setecientos cuarenta y siete"<<endl;
if(numeros==748)cout<< numeros<<" = setecientos cuarenta y ocho"<<endl;
if(numeros==749)cout<< numeros<<" = setecientos cuarenta y nueve"<<endl;
if(numeros==750)cout<< numeros<<" = setecientos cincuenta"<<endl;
if(numeros==751)cout<< numeros<<" = setecientos cincuenta y uno"<<endl;
if(numeros==752)cout<< numeros<<" = setecientos cincuenta y dos"<<endl;
if(numeros==753)cout<< numeros<<" = setecientos cincuenta y tres"<<endl;
if(numeros==754)cout<< numeros<<" = setecientos cincuenta y cuatro"<<endl;
if(numeros==755)cout<< numeros<<" =setecientos cincuenta y cinco"<<endl;
if(numeros==756)cout<< numeros<<" = setecientos cincuenta y seis"<<endl;
if(numeros==757)cout<< numeros<<" = setecientos cincuenta y siete"<<endl;
if(numeros==758)cout<< numeros<<" = setecientos ocincuenta y ocho"<<endl;
if(numeros==759)cout<< numeros<<" = setecientos cincuentaineve"<<endl;
if(numeros==760)cout<< numeros<<" = setecientos sesenta"<<endl;
if(numeros==761)cout<< numeros<<" = setecientos sesenta y uno"<<endl;
if(numeros==762)cout<< numeros<<" = setecientos sesenta y dos"<<endl;
if(numeros==763)cout<< numeros<<" = setecientos sesenta y tres"<<endl;
if(numeros==764)cout<< numeros<<" = setecientos sesenta  y cuatro"<<endl;
if(numeros==765)cout<< numeros<<" = setecientos sesenta y cinco"<<endl;
if(numeros==766)cout<< numeros<<" = setecientos sesenta y seis"<<endl;
if(numeros==767)cout<< numeros<<" = setecientos esenta y siete"<<endl;
if(numeros==768)cout<< numeros<<" = setecientos sesenta y ocho"<<endl;
if(numeros==769)cout<< numeros<<" = setecientos sesenta y nueve"<<endl;
if(numeros==770)cout<< numeros<<" = setecientos setenta"<<endl;
if(numeros==771)cout<< numeros<<" = setecientos setenta y uno"<<endl;
if(numeros==772)cout<< numeros<<" = setecientos setenta y dos"<<endl;
if(numeros==773)cout<< numeros<<" =setecientos setenta y tres"<<endl;
if(numeros==774)cout<< numeros<<" = setecientos setenta y cuatro"<<endl;
if(numeros==775)cout<< numeros<<" =setecientos setenta y cinco"<<endl;
if(numeros==776)cout<< numeros<<" =setecientos setenta y seis"<<endl;
if(numeros==777)cout<< numeros<<" = setecientos setenta y siete"<<endl;
if(numeros==778)cout<< numeros<<" = setecientos setenta y ocho"<<endl;
if(numeros==779)cout<< numeros<<" = setecientos setenta y nueve"<<endl;
if(numeros==780)cout<< " =setecientos ochenta"<<endl;
if(numeros==781)cout<< " =setecientos ochenta y uno"<<endl;
if(numeros==782)cout<< " = setecientos ochenta y dos"<<endl;
if(numeros==783)cout<<" =setecientos ochenta y tres"<<endl;
if(numeros==784)cout<<" =setecientos ochenta  y cuatro"<<endl;
if(numeros==785)cout<<" =setecientos ochenta y cinco"<<endl;
if(numeros==786)cout<<" =setecientos ochenta y seis"<<endl;
if(numeros==787)cout<<" =setecientos ochenta y siete"<<endl;
if(numeros==788)cout<<" =setecientos oochenta y ocho"<<endl;
if(numeros==789)cout<<" =setecientos ochenta y nueve"<<endl;
if(numeros==790)cout<<" = setecientos noventa"<<endl;
if(numeros==791)cout<<" = setecientos noventa y uno"<<endl;
if(numeros==792)cout<<" =setecientos noventa y dos"<<endl;
if(numeros==793)cout<<" = setecientos noventa y tres"<<endl;
if(numeros==794)cout<<" = setecientos noventa y cuatro"<<endl;
if(numeros==795)cout<<" = nsetecientos oventa y cinco"<<endl;
if(numeros==796)cout<<" = setecientos noventa y sesis"<<endl;
if(numeros==797)cout<<" = setecientos noventa y siete"<<endl;
if(numeros==798)cout<<" = setecientos noventa y ocho"<<endl;
if(numeros==799)cout<<" =setecientos noventa  ynueve"<<endl;
if(numeros==800)cout<<" =ochocientos"<<endl;
if (numeros==801)cout<< numeros<<" =ochocientos uno"<<endl;
if (numeros==802)cout<< numeros<<" =ochocientos dos"<<endl;
if(numeros==803)cout<< numeros<<" =ochocientos tres"<<endl;
if(numeros==804)cout<< numeros<<" =ochocientos cuatro"<<endl;
if(numeros==805)cout<< numeros<<" =ochocientos cinco"<<endl;
if(numeros==806)cout<< numeros<<" =ochocientos seis"<<endl;
if(numeros==807)cout<< numeros<<" =ochocientos siete"<<endl;
if(numeros==808)cout<< numeros<<" =ochocientos ocho"<<endl;
if(numeros==809)cout<< numeros<<" =ochocientos nueve"<<endl;
if(numeros==810)cout<< numeros<<" =ochocientos diez"<<endl;
if(numeros==811)cout<< numeros<<" =ochocientos once"<<endl;
if(numeros==812)cout<< numeros<<" =ochocientos doce"<<endl;
if(numeros==813)cout<< numeros<<" =ochocientos trece"<<endl;
if(numeros==814)cout<< numeros<<" = ochocientos catorce"<<endl;
if(numeros==815)cout<< numeros<<" =ochocientos quice"<<endl;
if(numeros==816)cout<< numeros<<" =ochocientos dieciseis"<<endl;
if(numeros==817)cout<< numeros<<" =ochocientos diecisiete"<<endl;
if(numeros==818)cout<< numeros<<" =ochocientos dieciocho"<<endl;
if(numeros==819)cout<< numeros<<" =ochocientos diecinueve"<<endl;
if(numeros==820)cout<< numeros<<" =ochocientos veinte"<<endl;
if(numeros==821)cout<< numeros<<" =ochocientos veintiuno"<<endl;
if(numeros==822)cout<< numeros<<" =ochocientos veintidos"<<endl;
if(numeros==823)cout<< numeros<<" =ochocientos veintitres"<<endl;
if(numeros==824)cout<< numeros<<" =ochocientos veinticuatro"<<endl;
if(numeros==825)cout<< numeros<<" =ochocientos veinticinco"<<endl;
if(numeros==826)cout<< numeros<<" =ochocientos veintiseis"<<endl;
if(numeros==827)cout<< numeros<<" =ochocientos veintisiete"<<endl;
if(numeros==828)cout<< numeros<<" =ochocientos veintiocho"<<endl;
if(numeros==829)cout<< numeros<<" =ochocientos veintinueve"<<endl;
if(numeros==830)cout<< numeros<<" =ochocientos treinta"<<endl;
if(numeros==831)cout<< numeros<<" =ochocientos treinta y uno"<<endl;
if(numeros==832)cout<< numeros<<" = ochocientos treinta y dos"<<endl;
if(numeros==833)cout<< numeros<<" =ochocientos treinta y tres"<<endl;
if(numeros==834)cout<< numeros<<" =ochocientos treinta y cuatro"<<endl;
if(numeros==835)cout<< numeros<<" =ochocientos treinta y cinco"<<endl;
if(numeros==836)cout<< numeros<<" =ochocientos treinta y seis"<<endl;
if(numeros==837)cout<< numeros<<" =ochocientos treinta y siete"<<endl;
if(numeros==838)cout<< numeros<<" =ochocientos treinta y ocho"<<endl;
if(numeros==839)cout<< numeros<<" =ochocientos treinta y nueve"<<endl;
if(numeros==840)cout<< numeros<<" =ochocientos cuarenta"<<endl;
if (numeros==841)cout<< numeros<<" = ochocientos cuarenta y uno"<<endl;
if (numeros==842)cout<< numeros<<" =ochocientos cuarenta y dos"<<endl;
if(numeros==843)cout<< numeros<<" =ochocientos cuarenta y tres"<<endl;
if(numeros==844)cout<< numeros<<" = ochocientoscuarenta y cuatro"<<endl;
if(numeros==845)cout<< numeros<<" = ochocientos cuarenta y cinco"<<endl;
if(numeros==846)cout<< numeros<<" = ochocientoscuarenta y seis"<<endl;
if(numeros==847)cout<< numeros<<" = ochocientos cuarenta y siete"<<endl;
if(numeros==848)cout<< numeros<<" = ochocientos cuarenta y ocho"<<endl;
if(numeros==849)cout<< numeros<<" = ochocientos cuarenta y nueve"<<endl;
if(numeros==850)cout<< numeros<<" = ochocientos cincuenta"<<endl;
if(numeros==851)cout<< numeros<<" = ochocientos cincuenta y uno"<<endl;
if(numeros==852)cout<< numeros<<" = ochocientos cincuenta y dos"<<endl;
if(numeros==853)cout<< numeros<<" = ochocientos cincuenta  y tres"<<endl;
if(numeros==854)cout<< numeros<<" = ochocientos cincuenta y cuatro"<<endl;
if(numeros==855)cout<< numeros<<" = ochocientos cincuenta y cinco"<<endl;
if(numeros==856)cout<< numeros<<" = ochocientos cincuenta y seis"<<endl;
if(numeros==857)cout<< numeros<<" = ochocientos cincuenta y siete"<<endl;
if(numeros==858)cout<< numeros<<" = ochocientos cincuenta y ocho"<<endl;
if(numeros==859)cout<< numeros<<" = ochocientos cincuenta y neve"<<endl;
if(numeros==860)cout<< numeros<<" = ochocientos sesenta"<<endl;
if(numeros==861)cout<< numeros<<" = ochocientos sesenta y uno"<<endl;
if(numeros==862)cout<< numeros<<" = ochocientos sesenta y dos"<<endl;
if(numeros==863)cout<< numeros<<" = ochocientos sesenta  y tres"<<endl;
if(numeros==864)cout<< numeros<<" = ochocientos sesenta y cuatro"<<endl;
if(numeros==865)cout<< numeros<<" = ochocientos sesenta y cinco"<<endl;
if(numeros==866)cout<< numeros<<" = ochocientos sesenta y seis"<<endl;
if(numeros==867)cout<< numeros<<" = ochocientos sesenta y siete"<<endl;
if(numeros==868)cout<< numeros<<" = ochocientos sesenta y ocho"<<endl;
if(numeros==869)cout<< numeros<<" = ochocientos sesenta y nueve"<<endl;
if(numeros==870)cout<< numeros<<" = ochocientos setenta"<<endl;
if(numeros==871)cout<< numeros<<" = ochocientos setenta y uno"<<endl;
if(numeros==872)cout<< numeros<<" = ochocientos setenta y dos"<<endl;
if(numeros==873)cout<< numeros<<" =  ochocientos setenta y tres"<<endl;
if(numeros==874)cout<< numeros<<" =  ochocientos setenta y cuatro"<<endl;
if(numeros==875)cout<< numeros<<" =ochocientos setenta y cinco"<<endl;
if(numeros==876)cout<< numeros<<" =ochocientos setenta y seis"<<endl;
if(numeros==877)cout<< numeros<<" = ochocientos setenta y siete"<<endl;
if(numeros==878)cout<< numeros<<" = ochocientos setenta y ocho"<<endl;
if(numeros==879)cout<< numeros<<" = ochocientos setenta y nueve"<<endl;
if(numeros==880)cout<< " =ochocientos ochenta"<<endl;
if(numeros==881)cout<< " =ochocientos ochenta y uno"<<endl;
if(numeros==882)cout<< " =ochocientos ochenta y dos"<<endl;
if(numeros==883)cout<<" = ochocientos ochenta y tres"<<endl;
if(numeros==884)cout<<" = ochocientos ochenta y cuatro"<<endl;
if(numeros==885)cout<<" = ochocientos ochenta y cinco"<<endl;
if(numeros==886)cout<<" = ochocientos ochenta y seis"<<endl;
if(numeros==887)cout<<" =ochocientos ochenta y siete"<<endl;
if(numeros==888)cout<<" =ochocientos ochenta y ocho"<<endl;
if(numeros==889)cout<<" =ochocientos ochenta y nueve"<<endl;
if(numeros==890)cout<<" =ochocientos noventa"<<endl;
if(numeros==891)cout<<" =ochocientos noventa y uno"<<endl;
if(numeros==892)cout<<" =ochocientos noventa y dos"<<endl;
if(numeros==893)cout<<" =ochocientos noventa y tres"<<endl;
if(numeros==894)cout<<" =ochocientos noventa y cuatro"<<endl;
if(numeros==895)cout<<" = ochocientos noventa y cinco"<<endl;
if(numeros==896)cout<<" =ochocientos noventa y sesis"<<endl;
if(numeros==897)cout<<" =ochocientos noventa y siete"<<endl;
if(numeros==898)cout<<" =ochocientos noventa y ocho"<<endl;
if(numeros==899)cout<<" =ochocientos noventa y nueve"<<endl;
if(numeros==900)cout<<" =novecientos "<<endl;
if (numeros==901)cout<< numeros<<" = novecientos  uno"<<endl;
if (numeros==902)cout<< numeros<<" = novecientos  dos"<<endl;
if(numeros==903)cout<< numeros<<" =  novecientos tres"<<endl;
if(numeros==904)cout<< numeros<<" = novecientos cuatro"<<endl;
if(numeros==905)cout<< numeros<<" = novecientos  cinco"<<endl;
if(numeros==906)cout<< numeros<<" = novecientos seis"<<endl;
if(numeros==907)cout<< numeros<<" = novecientos siete"<<endl;
if(numeros==908)cout<< numeros<<" = novecientos ocho"<<endl;
if(numeros==99)cout<< numeros<<" = novecientos nueve"<<endl;
if(numeros==910)cout<< numeros<<" = novecientos diez"<<endl;
if(numeros==911)cout<< numeros<<" = novecientos once"<<endl;
if(numeros==912)cout<< numeros<<" = novecientos doce"<<endl;
if(numeros==913)cout<< numeros<<" = novecientos trece"<<endl;
if(numeros==914)cout<< numeros<<" = novecientos catorce"<<endl;
if(numeros==915)cout<< numeros<<" = novecientos quice"<<endl;
if(numeros==916)cout<< numeros<<" = novecientos dieciseis"<<endl;
if(numeros==917)cout<< numeros<<" = novecientos diecisiete"<<endl;
if(numeros==918)cout<< numeros<<" = novecientos dieciocho"<<endl;
if(numeros==919)cout<< numeros<<" = novecientos diecinueve"<<endl;
if(numeros==920)cout<< numeros<<" = novecientos veinte"<<endl;
if(numeros==921)cout<< numeros<<" = novecientos veintiuno"<<endl;
if(numeros==922)cout<< numeros<<" = novecientos veintidos"<<endl;
if(numeros==923)cout<< numeros<<" = novecientos veintitres"<<endl;
if(numeros==924)cout<< numeros<<" = novecientos veinticuatro"<<endl;
if(numeros==925)cout<< numeros<<" = novecientos veinticinco"<<endl;
if(numeros==926)cout<< numeros<<" = novecientos veintiseis"<<endl;
if(numeros==927)cout<< numeros<<" = novecientos veintisiete"<<endl;
if(numeros==928)cout<< numeros<<" = novecientos veintiocho"<<endl;
if(numeros==929)cout<< numeros<<" = novecientos veintinueve"<<endl;
if(numeros==930)cout<< numeros<<" = novecientos treinta"<<endl;
if(numeros==931)cout<< numeros<<" = novecientos treinta y uno"<<endl;
if(numeros==932)cout<< numeros<<" = novecientos treinta y dos"<<endl;
if(numeros==933)cout<< numeros<<" = novecientos treinta y tres"<<endl;
if(numeros==934)cout<< numeros<<" = novecientos treinta y cuatro"<<endl;
if(numeros==935)cout<< numeros<<" =novecientos treinta y cinco"<<endl;
if(numeros==936)cout<< numeros<<" = novecientos treinta y seis"<<endl;
if(numeros==937)cout<< numeros<<" = novecientos treinta y siete"<<endl;
if(numeros==38)cout<< numeros<<" = treinta y ocho"<<endl;
if(numeros==939)cout<< numeros<<" = novecientos treinta y nueve"<<endl;
if(numeros==940)cout<< numeros<<" = novecientos cuarenta"<<endl;
if (numeros==941)cout<< numeros<<" = novecientos cuarenta y uno"<<endl;
if (numeros==942)cout<< numeros<<" = novecientos cuarenta y dos"<<endl;
if(numeros==943)cout<< numeros<<" = novecientos cuarenta y tres"<<endl;
if(numeros==944)cout<< numeros<<" = novecientos cuarenta y cuatro"<<endl;
if(numeros==945)cout<< numeros<<" = novecientos cuarenta y cinco"<<endl;
if(numeros==946)cout<< numeros<<" = novecientos cuarenta y seis"<<endl;
if(numeros==947)cout<< numeros<<" = novecientos cuarenta y siete"<<endl;
if(numeros==948)cout<< numeros<<" = novecientos cuarenta y ocho"<<endl;
if(numeros==949)cout<< numeros<<" = novecientos cuarenta y nueve"<<endl;
if(numeros==950)cout<< numeros<<" = novecientos cincuenta"<<endl;
if(numeros==951)cout<< numeros<<" = novecientos cincuenta y uno"<<endl;
if(numeros==952)cout<< numeros<<" = novecientos cincuenta y dos"<<endl;
if(numeros==953)cout<< numeros<<" = novecientos cincuenta y tres"<<endl;
if(numeros==954)cout<< numeros<<" = novecientos cincuenta y cuatro"<<endl;
if(numeros==955)cout<< numeros<<" = novecientos cincuenta y cinco"<<endl;
if(numeros==956)cout<< numeros<<" = novecientos cincuenta y seis"<<endl;
if(numeros==957)cout<< numeros<<" = novecientos cincuenta y siete"<<endl;
if(numeros==958)cout<< numeros<<" = novecientos cincuenta y ocho"<<endl;
if(numeros==959)cout<< numeros<<" = novecientos cincuenta y nueve"<<endl;
if(numeros==960)cout<< numeros<<" = novecientos sesenta"<<endl;
if(numeros==961)cout<< numeros<<" = novecientos sesenta y uno"<<endl;
if(numeros==962)cout<< numeros<<" = novecientos sesenta y dos"<<endl;
if(numeros==963)cout<< numeros<<" = novecientos sesenta y tres"<<endl;
if(numeros==964)cout<< numeros<<" = novecientos sesenta y cuatro"<<endl;
if(numeros==965)cout<< numeros<<" = novecientos sesenta y cinco"<<endl;
if(numeros==966)cout<< numeros<<" = novecientos sesenta y seis"<<endl;
if(numeros==967)cout<< numeros<<" = novecientos sesenta y siete"<<endl;
if(numeros==968)cout<< numeros<<" = novecientos sesenta y ocho"<<endl;
if(numeros==969)cout<< numeros<<" = novecientos sesenta y nueve"<<endl;
if(numeros==970)cout<< numeros<<" = novecientos setenta"<<endl;
if(numeros==971)cout<< numeros<<" = novecientos setenta y uno"<<endl;
if(numeros==972)cout<< numeros<<" = novecientos setenta y dos"<<endl;
if(numeros==973)cout<< numeros<<" = novecientos setenta y tres"<<endl;
if(numeros==974)cout<< numeros<<" = novecientos setenta y cuatro"<<endl;
if(numeros==975)cout<< numeros<<" = novecientos setenta y cinco"<<endl;
if(numeros==976)cout<< numeros<<" = novecientos setenta y seis"<<endl;
if(numeros==977)cout<< numeros<<" = novecientos setenta y siete"<<endl;
if(numeros==978)cout<< numeros<<" = novecientos setenta y ocho"<<endl;
if(numeros==979)cout<< numeros<<" = novecientos setenta y nueve"<<endl;
if(numeros==980)cout<< " = novecientos ochenta"<<endl;
if(numeros==981)cout<< " = novecientos ochenta y uno"<<endl;
if(numeros==982)cout<< " = novecientos ochenta y dos"<<endl;
if(numeros==983)cout<<" = novecientos ochenta y tres"<<endl;
if(numeros==984)cout<<" = novecientos ochenta y cuatro"<<endl;
if(numeros==985)cout<<" =novecientos  ochenta y cinco"<<endl;
if(numeros==986)cout<<" = novecientos ochenta y seis"<<endl;
if(numeros==987)cout<<" =novecientos ochenta y siete"<<endl;
if(numeros==988)cout<<" = novecientos ochenta y ocho"<<endl;
if(numeros==989)cout<<" = novecientos ochenta y nueve"<<endl;
if(numeros==90)cout<<" = novecientos noventa"<<endl;
if(numeros==991)cout<<" =novecientos noventa y uno"<<endl;
if(numeros==992)cout<<" =novecientos noventa y dos"<<endl;
if(numeros==993)cout<<" =novecientos noventa y tres"<<endl;
if(numeros==94)cout<<" =novecientos noventa y cuatro"<<endl;
if(numeros==995)cout<<" = novecientos noventa y cinco"<<endl;
if(numeros==996)cout<<" =novecientos noventa y sesis"<<endl;
if(numeros==997)cout<<" =novecientos noventa y siete"<<endl;
if(numeros==998)cout<<" =novecientos noventa y ocho"<<endl;
if(numeros==999)cout<<" =novencientos noventa y nueve"<<endl;
return 0;
}
